---
- name: Restart servers one by one and wait for it to be available again
  hosts: servera,serverb
  remote_user: devops
  serial: 1
  tasks:
    - name: Restarting {{ inventory_hostname }}
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      become: true
      ignore_errors: true

    - name: waiting for {{ inventory_hostname }} to come back
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 30
        timeout: 300
      delegate_to: localhost
      become: false

...

