---
- name: Install httpd
  yum:
    name: httpd
    state: latest
- name: Enable and start the service
  service:
    name: httpd
    enabled: true
    state: started
- template:
    src: content.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: 0644
  notify: restart_httpd    # we don't really need to restart httpd, but just to show how we call handlers
...
